[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Matheus Marques Gobetti", email = "gobetti.ifc@gmail.com"},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

