[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Matheus Marques Gobetti", email = "gobetti.ifc@gmail.com"},
]
dependencies = [
    "django>=4.2.6",
    "djangorestframework>=3.14.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.7.0",
]
